/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ThreeIdKeychain {
  authMap?: {
    [k: string]: AuthData;
  };
  pastSeeds?: JWE[];
}
export interface AuthData {
  id?: WrappedJWE;
  pub?: string;
  data?: WrappedJWE;
}
export interface WrappedJWE {
  jwe?: JWE;
}
export interface JWE {
  protected: string;
  iv: string;
  ciphertext: string;
  tag: string;
  aad?: string;
  recipients?: {
    header: {
      [k: string]: unknown;
    };
    encrypted_key: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
