/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CeramicDocId = string;

/**
 * A [[ClaimedCredential]] represents a specific, factually-oriented claim that could be the Id and CredentialSubject of a [[VerifiableCredential]]
 */
export interface ClaimedCredential {
  did: string;
  type: string;
  typeSchema?: string;
  value?: {
    keccak256?: string;
    value?: string;
    description?: string;
    country?: string;
    city?: string;
    postalCode?: string;
    date?: string;
    time?: string;
    startDate?: string;
    endDate?: string;
    issuanceDate?: string;
    expirationDate?: string;
    issuingEntity?: string;
    imageIPFS?: string;
    [k: string]: unknown;
  };
  encrypted?: JWE;
  verifiableCredentials?: CeramicDocId[];
}
export interface JWE {
  protected: string;
  iv: string;
  ciphertext: string;
  tag: string;
  aad?: string;
  recipients?: {
    header: {
      alg: string;
      iv: string;
      tag: string;
      epk?: {
        [k: string]: unknown;
      };
      kid?: string;
      [k: string]: unknown;
    };
    encrypted_key: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
