/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CeramicDocId = string

/**
 * The [[ClaimedCredentials]] holds the list of claimed [[ClaimedCredential]] by the user
 */
export interface ClaimedCredentials {
  claimed?: CeramicDocId[]
}
