/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CeramicDocId = string;

/**
 * The [[IssuedCredentials]] holds the list of [[VerifiableCredential]] issued by the user
 */
export interface IssuedCredentials {
  issued?: CeramicDocId[];
}
