/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SocialConnection {
  outboundLink?: Connection[];
  [k: string]: unknown;
}
export interface Connection {
  /**
   * The type of this connection e.g. follow/own.
   */
  connectionType?: string;
  /**
   * The target of such connection e.g. DID or address.
   */
  target?: string;
  /**
   * The namespace of this connection.
   */
  namespace?: string;
  /**
   * The date of this connection.
   */
  createdAt?: string;
  /**
   * The alias of this target.
   */
  alias?: string;
  [k: string]: unknown;
}
