/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A lightweight schema for skills and credentials
 */
export interface BasicSkills {
  skills?: BasicSkill[];
  [k: string]: unknown;
}
export interface BasicSkill {
  /**
   * A human readable name for the skill.
   */
  name: string;
  /**
   * A unique identifier (e.g. uuid or uri) to allow applications to use this skill.
   */
  id: string;
  /**
   * An optional description to add more details.
   */
  description?: string;
  /**
   * Tags to allow easier searching of skills.
   */
  tags?: string[];
  /**
   * An optional image to use when displaying the skill.
   */
  image?: string;
  /**
   * A link to a document giving details about the status of the skill. E.g. terms of use / revocation status.
   */
  details?: string;
  /**
   * A unique identifier representing an issuer of the skill (e.g. did of an institution).
   */
  issuer?: string;
  /**
   * The date the skill was obtained (ISO8601 DateTime format).
   */
  issuedDate?: string;
  /**
   * The date the skill expires / must be renewed (ISO8601 DateTime format).
   */
  expiresDate?: string;
  /**
   * A proof mechanism to verify that the issuer certifies the skill. Based on https://www.w3.org/TR/vc-data-model/#proofs-signatures.
   */
  issuerVerification?: {
    /**
     * The signature method (e.g. RsaSignature2018).
     */
    type?: string;
    /**
     * A resource (e.g. URI) that contains the information required to perform the verification process.
     */
    verificationMethod?: string;
    /**
     * The signature to use in the verification process (e.g. JSON Web Signature).
     */
    sig?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
