/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IPFSUrl = string;
export type PositiveInteger = number;

export interface BasicProfile {
  name?: string;
  image?: ImageSources;
  description?: string;
  emoji?: string;
  background?: ImageSources;
  birthDate?: string;
  url?: string;
  gender?: string;
  homeLocation?: string;
  residenceCountry?: string;
  nationalities?: [string, ...string[]];
  affiliations?: string[];
  [k: string]: unknown;
}
export interface ImageSources {
  original: ImageMetadata;
  alternatives?: ImageMetadata[];
  [k: string]: unknown;
}
export interface ImageMetadata {
  src: IPFSUrl;
  mimeType: string;
  width: PositiveInteger;
  height: PositiveInteger;
  size?: PositiveInteger;
  [k: string]: unknown;
}
