/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TheNameSchema = string
export type TheImageSchema = string
export type TheDescriptionSchema = string
export type TheExternalUrlSchema = string

export interface OpenSeaNftMetadata {
  name?: TheNameSchema
  image?: TheImageSchema
  attributes?: Array<{
    value: number | string
    trait_type: string
    display_type?: string
    [k: string]: unknown
  }>
  description?: TheDescriptionSchema
  external_url?: TheExternalUrlSchema
  [k: string]: unknown
}
