/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CeramicDocId = string;

/**
 * A [[VerifiableCredential]] is fact-checking review/attestation of claims made (or reported) in a [[ClaimedCredential]]
 */
export interface VerifiableCredential {
  "@context"?: string[];
  _context?: string;
  type?: string[];
  _type?: string;
  id: CeramicDocId;
  issuer: {
    id: string;
    ethereumAddress?: string;
    [k: string]: unknown;
  };
  credentialSubject: {
    id: string;
    ethereumAddress?: string;
    [k: string]: unknown;
  };
  credentialSchema: {
    id: string;
    type?: string;
    _type?: string;
    [k: string]: unknown;
  };
  issuanceDate: string;
  expirationDate?: string;
  proof?: {
    [k: string]: unknown;
  };
  evidence?: {
    [k: string]: unknown;
  };
}
