/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CeramicDocId = string;

/**
 * A [[ClaimedCredential]] represents a specific, factually-oriented claim that could be the CredentialSubject in a [[VerifiableCredential]]
 */
export interface ClaimedCredential {
  did: string;
  type: string;
  typeSchema?: CeramicDocId;
  value?: {
    [k: string]: unknown;
  };
  encrypted: JWE;
  verifiableCredentials?: CeramicDocId[];
}
export interface JWE {
  protected: string;
  iv: string;
  ciphertext: string;
  tag: string;
  aad?: string;
  recipients?: {
    header: {
      alg: string;
      iv: string;
      tag: string;
      epk?: {
        [k: string]: unknown;
      };
      kid?: string;
      [k: string]: unknown;
    };
    encrypted_key: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
