/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AddressBook {
  /**
   * The total number of contacts
   */
  total_cnt: number;
  contacts: {
    /**
     * The contact's name
     */
    name: string;
    /**
     * Collection of the contact's wallet addresses and respective networks
     */
    wallets: {
      walletAddress: string;
      network: string;
    }[];
    /**
     * Optional URI of user avatar
     */
    avatar?: string;
    /**
     * Optional tags for the contact
     */
    tags?: [string, ...string[]];
    /**
     * Fields to include optional arbitrary data
     */
    data?: {
      [k: string]: unknown;
    };
  }[];
}
