/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DIDToAddressBook {
  mapping: {
    /**
     * The user's DID
     */
    user_DID: string;
    /**
     * The streamID of the Address Book associated to the user
     */
    address_book_streamID: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
