/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CryptoAccountLinks {
  /**
   * This interface was referenced by `CryptoAccountLinks`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9]{1,63}@[-a-zA-Z0-9]{3,16}:[-a-zA-Z0-9]{1,47}".
   */
  [k: string]: string;
}
