/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * hash of the transaction
 */
export type TxHash = string;
/**
 * whether or not DID is payer
 */
export type IsPayer = boolean;
/**
 * work summary
 */
export type Summary = string;
/**
 * current formats are url or cid
 */
export type Format = string;
/**
 * work deliverable value(url/cid)
 */
export type Value = string;
/**
 * work deliverables
 */
export type Deliverables = DeliverableItem[];
/**
 * fiat price at the time of the transaction
 */
export type Value1 = string;
/**
 * work genre e.g, Dev, Design etc
 */
export type Genre = string;
/**
 * hash value of all work descriptions(summary, detail, deliverables)
 */
export type DeliverableHash = string;
/**
 * a transaction platform if exists e.g, gitcoin
 */
export type Platform = string;
/**
 * Either both signatures exist or the transaction is via platform
 */
export type IsVerified = boolean;
/**
 * Time stamp of transaction occurrence
 */
export type IssuedTimestamp = string;
export type WorkCredentials1 = WorkCredentialItem[];

export interface WorkCredentials {
  WorkCredentials?: WorkCredentials1;
}
/**
 * work credential id
 */
export interface WorkCredentialItem {
  id?: string;
  txHash?: TxHash;
  isPayer?: IsPayer;
  summary?: Summary;
  deliverables?: Deliverables;
  fiatValue?: Value1;
  genre?: Genre;
  deliverableHash?: DeliverableHash;
  platform?: Platform;
  isVerified?: IsVerified;
  issuedTimestamp?: IssuedTimestamp;
  [k: string]: unknown;
}
export interface DeliverableItem {
  format?: Format;
  value?: Value;
  [k: string]: unknown;
}
